### ISSUE TITLE
Native property access doesn’t work in production

### ISSUE THREAD

**Issue by mogstad** [hjdivad/ember-m3#1371]
When running m3 in a production build using native properties doesn’t work, as `megamorphicModelProxyHandler` isn’t defined, and the proxy constructor throws an error. It’s only defined inside an `if (DEBUG)` statement, making it work fine in development builds. 

Would it be sufficient to move the declaration outside of that if statement, or is there a reason it’s inside it?

Code ref: https://github.com/hjdivad/ember-m3/blob/master/addon/model.js#L115

**Comment by hjdivad** [comment]
@mogstad thanks very much for reporting this; we should have this fixed soon (probably today); see #1376
