### ISSUE TITLE
add api for inserting directly into the query cache

### ISSUE THREAD

**Issue by hjdivad** [hjdivad/ember-m3#140]
```js
store.queryURL(url, { cacheKey }).then(result => {
  store.cacheURL( computeSecondaryCacheKey(cacheKey, result), result);
})
```

unsure about name, intended to fit with [these](https://github.com/hjdivad/ember-m3/blob/master/addon/initializers/m3-store.js#L57-L67)

---

This is helpful for eg querying an seo-friendly "clean" url but still caching it for a subsequent app generated "dirty" url.

**Comment by hjdivad** [comment]
cc @sangm

**Comment by sangm** [comment]
I'll work on the PR _under_ the assumption that we name it `cacheURL`.

We can discuss renaming it after the work is complete 😄
