### ISSUE TITLE
Native proxy intercepts symbols in tests for attribute access

### ISSUE THREAD

**Issue by runspired** [hjdivad/ember-m3#1569]
This leads to a test failure for the wrong key having been seen. I noticed this when adding  DEBUG symbols in ember-data that attach the record identifier to the record via Symbol. We ended up adding a hack (don't attempt to attach if the record is a Proxy instance) in ember-data to avoid breaking m3's tests for now, but we would like to remove the hack as it will limit our own usage of Proxy.

**Comment by hjdivad** [comment]
@runspired can't you achieve the same effect more robustly with a `WeakMap` rather than mutating the class?

That said, the point of this proxy is to sit between userland + payloads so there's no real value in intercepting symbols.

**Comment by runspired** [comment]
In prod we do use a WeakMap, the symbol is to make it easier for consumers to debug in Dev builds

**Comment by hjdivad** [comment]
@runspired got it so the motivation here is discoverability?  that makes a  ton of sense

**Comment by larry-x-yu** [comment]
@runspired, do you think the test case in this PR captures your expectation for the request?
https://github.com/hjdivad/ember-m3/pull/1626
