### ISSUE TITLE
`eachAttribute` does not correctly get the data from the base model data

### ISSUE THREAD

**Issue by dnachev** [hjdivad/ember-m3#165]
The implementation relies on the projection model data's own `_data` object, which is empty, because all of the data from the projections should come from the base model data.

**Comment by hjdivad** [comment]
@dnachev presumably this prevents serializing any projection?

**Comment by dnachev** [comment]
When I submitted the issue it was just by looking at the code, but the `_data` is actually delegated to the base model, therefore `eachAttribute()` can afford to not delegate as well, because it is working on top of the correct data.

**Comment by hjdivad** [comment]
related: #168
