### ISSUE TITLE
Remove dependency on ember-data?

### ISSUE THREAD

**Issue by rwjblue** [hjdivad/ember-m3#18]
It seems likely that we want to remove `ember-data` as a direct dependency of this addon, and instead use the host project's version, right?

- [ ] Move `ember-data` to `devDependencies`
- [ ] Add `ember-data` to `peerDependencies` 

ember-cli does not yet have any special handling of `peerDependencies`, but `npm` and `yarn` both provide nice warnings when they are not satisfied...

**Comment by stefanpenner** [comment]
>  Move ember-data to devDependencies

This is my vote. With an assertion if ember-data is at the right version is not present (either from the build side, or runtime, likely build side)
