### ISSUE TITLE
How to configure ember-m3 to ember app

### ISSUE THREAD

**Issue by pranavdubase** [hjdivad/ember-m3#206]
I am new to ember and trying to add `ember-m3' in my app. How to configure model,adapters and service with route model ?

**Comment by hjdivad** [comment]
Hi @pranavdubase 

If you're new to ember it's likely going to be easier to use [ember-data](https://github.com/emberjs/data) with the default `DS.Model` modeling layer.  The [guides](https://guides.emberjs.com/release/models/) are a great resource for this.

---

But to answer your questions specifically

1. You will typically use only your `application` adapter with ember-m3.  You can create one with `ember generate adapter application`
2. If some of your models are using ember-m3 and others are using `DS.Model` you will likely want an m3-specific adapter.  You can create one with `ember generate adapter -ember-m3`.  This is generally useful when migrating an existing app to use ember-m3.
3. There's an example schema service in [README.md](https://github.com/hjdivad/ember-m3/blob/c320150d33e833b3ba62389b50cada0b42781a63/README.md) -- you can generate one with `ember generate service m3-schema`

You don't configure models individually with ember-m3 -- it uses a single, dynamic, model to give you a way to interact with your API's payload.  This is what makes it useful for APIs that are either very dynamic or have a very large number of types.

**Comment by hjdivad** [comment]
I'd also strongly encourage you to check out the [ember community discord](https://discordapp.com/invite/zT3asNS) and [other community resources](https://emberjs.com/community/).

Hopefully this is helpful.

Cheers.
