### ISSUE TITLE
add support for queryURL returning primitives

### ISSUE THREAD

**Issue by hjdivad** [hjdivad/ember-m3#750]

**Comment by rwjblue** [comment]
Sorry, I'm not picturing the use case here, can you give a usage scenario?

**Comment by hjdivad** [comment]
@rwjblue querying something like a [rest.li action](https://linkedin.github.io/rest.li/spec/protocol#actions) that returns a `string`.

Right now [_createResult](https://github.com/hjdivad/ember-m3/blob/4c3e3614ed98e328150b7add66598c54c906d226/addon/query-cache.js#L201-L207) assumes the result is either empty or something that we can `store.push`.

If you're asking why use `queryURL` when the server responds like this, there's a couple of reasons:

1. The server may return a union that's sometimes a primitive and sometimes an object.
2. To make it easier for users to just "always use queryURL" and maintain a simpler mental model.

@rwjblue thoughts?

**Comment by rwjblue** [comment]
Ya, makes total sense. I just hadn't seen / dealt with a server that wants to respond with a string instead of JSON object/array/etc.
