### ISSUE TITLE
Make the params option for queryURL more explicit

### ISSUE THREAD

**Issue by 2hu12** [hjdivad/ember-m3#782]
The current `params` option has different effect for `GET` and `POST` which is like the `data` option for `jQuery.ajax`.

But it will be inconvenient for `POST` method url with query parameters, this is common for some api design like “rest.li”.

Could we split this `params` into two options, for example, `queryParams` and `payload` or some more idiomatic option names? For `GET` it can only have `queryParams` and for `POST` it can have both.

**Comment by 2hu12** [comment]
I'd like to take this task, but I'm kinda uncertain about where should we place this modification, `ember-m3/query-cache` or `RESTAdapter.ajax` method. I think I do it in `ember-m3` at first.

**Comment by hjdivad** [comment]
@2hu12 if you have time to contribute that would be great.  I think we'd want to do this in `query-cache`, either in or before we get to `_adapterQueryURL`.

Not sure what the best API is but maybe something like `params` and `urlParams`, where the latter are added to the URL and the former are treated as they currently are (where we hand them off to either `adapter.queryURL` or `adapter.ajax`)

**Comment by hjdivad** [comment]
fixed in #784
