### ISSUE TITLE
Add queryParams PR #784 to the next release

### ISSUE THREAD

**Issue by steventsao** [hjdivad/ember-m3#969]
Can the next release include this PR? https://github.com/hjdivad/ember-m3/pull/784

I see it in master but not in [v3.0.4](https://github.com/hjdivad/ember-m3/blob/v3.0.4/addon/query-cache.js). Thanks!

**Comment by steventsao** [comment]
Hi, is there a release planned in a week or two? Thanks! @hjdivad

**Comment by hjdivad** [comment]
backporting in #980 then I'll cut a 3.x release
